config/routes.rb
InfiniteScrolling::Application.routes.draw do
  resources :posts, only: [:index, :show]

  get '/posts_with_button', to: 'posts#index_with_button', as: 'posts_with_button'

  root to: 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :body, :title

  def timestamp
    created_at.strftime('%d %B %Y %H:%M:%S')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    get_and_show_posts
  end

  def index_with_button
    get_and_show_posts
  end

  def show
    @post = Post.find_by_id(params[:id])
  end

  private

  def get_and_show_posts
    @posts = Post.paginate(page: params[:page], per_page: 15).order('created_at DESC')
    respond_to do |format|
      format.html
      format.js
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>InfiniteScrolling</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'shared/top_menu' %>

<div class="container">
  <%= yield %>
</div>

<%= render 'shared/footer' %>

</body>
</html>

app/views/posts/_post.html.erb
<div>
  <h2><%= link_to post.title, post_path(post) %></h2>

  <small><em><%= post.timestamp %></em></small>

  <p><%= truncate(strip_tags(post.body), length: 600) %></p>
</div>

app/views/posts/index.html.erb
<div class="page-header">
  <h1>My posts</h1>
</div>

<div id="static-pagination">
  <%= will_paginate %>
</div>

<div id="my-posts">
  <div class="page-delimiter first-page" data-page="<%= params[:page] || 1 %>"></div>
  <%= render @posts %>
</div>

<% if @posts.next_page %>
    <div id="infinite-scrolling">
      <%= will_paginate %>
    </div>
<% end %>

app/views/posts/index.js.erb
var delimiter =
        $('<div class="page-delimiter" data-page="<%= params[:page] %>"></div>');
$('#my-posts').append(delimiter);
$('#my-posts').append('<%= j render @posts %>');
$('.pagination').replaceWith('<%= j will_paginate @posts %>');
preparePagination(delimiter);
<% unless @posts.next_page %>
$('#infinite-scrolling .pagination').remove();
<% end %>

app/views/posts/index_with_button.html.erb
<div class="page-header">
  <h1>My posts</h1>
</div>

<div id="static-pagination">
  <%= will_paginate %>
</div>

<div id="my-posts">
  <div class="page-delimiter first-page" data-page="<%= params[:page] || 1 %>"></div>
  <%= render @posts %>
</div>

<% if @posts.next_page %>
    <div id="with-button">
      <%= will_paginate %>
    </div>

    <div id="load_more_posts" class="btn btn-primary btn-lg">More posts</div>
<% end %>

app/views/posts/index_with_button.js.erb
var delimiter =
        $('<div class="page-delimiter" data-page="<%= params[:page] %>"></div>');
$('#my-posts').append(delimiter);
$('#my-posts').append('<%= j render @posts %>');
$('.pagination').replaceWith('<%= j will_paginate @posts %>');
preparePagination(delimiter);
<% if @posts.next_page %>
$('#with-button .pagination').hide();
<% else %>
$('#with-button .pagination, #load_more_posts').remove();
<% end %>

app/views/posts/show.html.erb
<div class="page-header">
  <h1><%= @post.title %></h1>
</div>

<%= @post.body.html_safe %>

app/views/shared/_footer.html.erb
<div id="footer">
  <div class="container">
    <p class="text-muted">&copy; My Company</p>
  </div>
</div>

app/views/shared/_top_menu.html.erb
<div class="navbar navbar-inverse" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to 'True Infite Scrolling', root_url %></li>
        <li><%= link_to 'With Button', posts_with_button_url %></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>